# https://taskfile.dev

version: "3"

silent: true

tasks:
  test:
    cmds:
      - go test -v -race ./...

  generate:
    cmds:
      - go generate ./...
    aliases:
      - gen
    generates:
      - ./**/mock/*.go
    sources:
      - ./internal/*/*.go

  docs:
    cmds:
      - go run bin/docs/main.go -version {{ .CLI_ARGS }}
    desc: Generate docs

  build:
    cmds:
      - go build -o ./bin/ -ldflags "-s -w" .
