name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install dependencies
        run: go mod download

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install dependencies
        run: go mod download

      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test -v -race ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install dependencies
        run: go mod download

      - name: Generate
        run: go generate ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
